app = "multi-blog-service"
primary_region = "lhr"

[build]
command = "./gradlew build"

[env]
PORT = "8080"
SPRING_PROFILES_ACTIVE = "cloud"

[[services]]
protocol = "tcp"
internal_port = 8080
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]
[[services.ports]]
port = 443
handlers = ["tls", "http"]

[[services.http_checks]]
interval = "10s"
timeout = "2s"
grace_period = "5s"
method = "get"
path = "/actuator/health"
protocol = "http"

[processes]
app = "java -Xmx300m -Xms300m -jar -Dspring.profiles.active=cloud -Dserver.address=0.0.0.0 -Dserver.port=8080 app.jar"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
